[package]
name = "iamge_pixel_sorting"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { version = "^1.1", features = ["fltk-bundled"] }
fltk-flex = "0.1"
image = "0.23.14"